"""
Готовая лексика по темам — 500+ слов для повседневного использования.
"""

VOCABULARY_THEMES = {
    "travel": {
        "name": "✈️ Путешествия",
        "words": [
            ("departure", "отправление", "What time is the departure?"),
            ("arrival", "прибытие", "The arrival is at 5 PM."),
            ("boarding pass", "посадочный талон", "Please show your boarding pass."),
            ("luggage", "багаж", "I lost my luggage at the airport."),
            ("passport", "паспорт", "Don't forget your passport!"),
            ("customs", "таможня", "You need to go through customs."),
            ("check-in", "регистрация", "Check-in opens two hours before the flight."),
            ("destination", "пункт назначения", "What is your final destination?"),
            ("itinerary", "маршрут", "Let me check the itinerary."),
            ("accommodation", "проживание", "Have you booked accommodation?"),
            ("exchange rate", "курс обмена", "What's the exchange rate today?"),
            ("souvenir", "сувенир", "I bought a souvenir for my mom."),
            ("sightseeing", "осмотр достопримечательностей", "We went sightseeing all day."),
            ("jet lag", "джетлаг", "I'm suffering from jet lag."),
            ("delay", "задержка", "The flight has a two-hour delay."),
            ("transit", "транзит", "I have a transit stop in Dubai."),
            ("visa", "виза", "I need a visa for this country."),
            ("currency", "валюта", "What currency do they use here?"),
            ("one-way ticket", "билет в одну сторону", "I bought a one-way ticket."),
            ("round trip", "туда и обратно", "A round trip is cheaper."),
            ("hostel", "хостел", "I stayed at a hostel to save money."),
            ("backpacker", "путешественник с рюкзаком", "I was a backpacker in my twenties."),
            ("layover", "пересадка", "I have a 3-hour layover in Frankfurt."),
            ("overhead bin", "верхняя полка в самолёте", "Put your bag in the overhead bin."),
            ("aisle seat", "место у прохода", "I prefer an aisle seat."),
            ("window seat", "место у окна", "Can I have the window seat?"),
            ("immigration", "иммиграционный контроль", "Immigration took 40 minutes."),
            ("shuttle bus", "шаттл/автобус-перевозчик", "Take the shuttle bus to the hotel."),
            ("travel insurance", "страховка путешественника", "Always get travel insurance."),
            ("guidebook", "путеводитель", "I bought a guidebook for Rome."),
            ("local", "местный житель", "Ask a local for recommendations."),
            ("off the beaten path", "вдали от туристических троп", "I love off the beaten path places."),
            ("peak season", "высокий сезон", "Avoid peak season if you can."),
            ("package tour", "пакетный тур", "We booked a package tour."),
            ("public transport", "общественный транспорт", "Use public transport in the city."),
        ]
    },
    "food": {
        "name": "🍕 Еда и рестораны",
        "words": [
            ("appetizer", "закуска", "Let's order some appetizers first."),
            ("main course", "основное блюдо", "I'll have the pasta as my main course."),
            ("dessert", "десерт", "Do you have any desserts?"),
            ("ingredient", "ингредиент", "What ingredients are in this dish?"),
            ("recipe", "рецепт", "Can you share the recipe?"),
            ("spicy", "острый", "Is this dish spicy?"),
            ("delicious", "вкусный", "This is absolutely delicious!"),
            ("portion", "порция", "The portions are very generous here."),
            ("bill", "счёт", "Could we have the bill, please?"),
            ("tip", "чаевые", "Don't forget to leave a tip."),
            ("reservation", "бронирование", "I have a reservation for two."),
            ("vegetarian", "вегетарианский", "Do you have vegetarian options?"),
            ("allergen", "аллерген", "Any allergens I should know about?"),
            ("takeaway", "еда навынос", "Can I order takeaway?"),
            ("fresh", "свежий", "The vegetables look very fresh."),
            ("grilled", "приготовленный на гриле", "I'd like the grilled chicken."),
            ("medium-rare", "средняя прожарка", "I'll have my steak medium-rare."),
            ("overcooked", "пережаренный", "My steak is overcooked, sorry."),
            ("to taste", "по вкусу", "Add salt and pepper to taste."),
            ("sour", "кислый", "This lemon is very sour."),
            ("bitter", "горький", "Dark chocolate is quite bitter."),
            ("sweet", "сладкий", "This mango is very sweet."),
            ("savoury", "солёный/пикантный", "I prefer savoury over sweet."),
            ("crispy", "хрустящий", "The fried chicken is crispy!"),
            ("tender", "нежный/мягкий", "The meat is very tender."),
            ("marinated", "маринованный", "The chicken was marinated overnight."),
            ("steamed", "приготовленный на пару", "Steamed vegetables are healthier."),
            ("dressing", "соус/заправка", "What dressing would you like?"),
            ("gluten-free", "без глютена", "Is there a gluten-free option?"),
            ("dairy-free", "без молочных продуктов", "I need a dairy-free dessert."),
            ("buffet", "шведский стол", "The hotel has a breakfast buffet."),
            ("chef", "шеф-повар", "The chef trained in Paris."),
            ("seasoning", "приправа", "What seasoning is in this sauce?"),
            ("portion size", "размер порции", "The portion sizes here are huge!"),
            ("complimentary", "бесплатный/комплиментарный", "Bread is complimentary here."),
        ]
    },
    "work": {
        "name": "💼 Работа и карьера",
        "words": [
            ("deadline", "дедлайн", "The deadline is tomorrow morning."),
            ("colleague", "коллега", "My colleague helped me with the report."),
            ("salary", "зарплата", "Have you discussed the salary?"),
            ("promotion", "повышение", "She got a promotion last month."),
            ("meeting", "встреча/совещание", "I have a meeting at 3 PM."),
            ("project", "проект", "We launched a new project this week."),
            ("feedback", "обратная связь", "Can you give me feedback on my work?"),
            ("resignation", "увольнение", "He submitted his resignation yesterday."),
            ("interview", "собеседование", "I have a job interview tomorrow."),
            ("remote work", "удалённая работа", "I prefer remote work."),
            ("overtime", "сверхурочные", "I worked overtime this week."),
            ("budget", "бюджет", "We need to stay within budget."),
            ("proposal", "предложение/проект", "I'll send you the proposal today."),
            ("teamwork", "командная работа", "Teamwork makes the dream work!"),
            ("negotiate", "вести переговоры", "I need to negotiate a raise."),
            ("client", "клиент", "The client loved our presentation."),
            ("spreadsheet", "таблица", "Please update the spreadsheet."),
            ("agenda", "повестка дня", "What's on the agenda today?"),
            ("workload", "рабочая нагрузка", "My workload is overwhelming."),
            ("achievement", "достижение", "List your achievements on your CV."),
            ("performance review", "оценка работы", "My performance review is next week."),
            ("job description", "должностная инструкция", "The job description was very detailed."),
            ("probation period", "испытательный срок", "I'm still on probation."),
            ("benefits", "льготы", "The benefits package is excellent."),
            ("networking", "нетворкинг", "Networking is key in this industry."),
            ("reference", "рекомендация", "Can you be my reference?"),
            ("resign", "уволиться", "She decided to resign last Friday."),
            ("hire", "нанять", "We need to hire two more people."),
            ("brainstorm", "мозговой штурм", "Let's brainstorm some ideas."),
            ("presentation", "презентация", "The presentation went very well."),
            ("conference call", "конференц-звонок", "We have a conference call at noon."),
            ("handover", "передача дел", "I did a full handover before leaving."),
            ("outsource", "аутсорсинг", "We decided to outsource the design."),
            ("quarterly", "ежеквартально", "We have quarterly reviews."),
            ("KPI", "ключевые показатели", "Did you hit your KPIs this quarter?"),
        ]
    },
    "daily": {
        "name": "🏠 Повседневная жизнь",
        "words": [
            ("routine", "распорядок дня", "I have a morning routine."),
            ("commute", "дорога на работу", "My commute takes 40 minutes."),
            ("chores", "домашние дела", "I hate doing chores on weekends."),
            ("grocery", "продукты", "I need to buy groceries."),
            ("landlord", "хозяин жилья", "My landlord raised the rent."),
            ("utility bills", "коммунальные платежи", "Utility bills are expensive."),
            ("neighbourhood", "район", "I love my neighbourhood."),
            ("schedule", "расписание", "What's your schedule tomorrow?"),
            ("appointment", "запись/встреча", "I have a dentist appointment."),
            ("errand", "дело/поручение", "I have some errands to run."),
            ("habit", "привычка", "Reading is a good habit."),
            ("queue", "очередь", "There's a long queue at the shop."),
            ("receipt", "чек", "Keep the receipt for the return."),
            ("subscription", "подписка", "I cancelled my Netflix subscription."),
            ("delivery", "доставка", "The delivery will arrive tomorrow."),
            ("mortgage", "ипотека", "They took out a mortgage."),
            ("laundry", "стирка", "I need to do the laundry."),
            ("rush hour", "час пик", "Avoid driving during rush hour."),
            ("alarm clock", "будильник", "I set three alarm clocks."),
            ("nap", "короткий сон", "I took a nap after lunch."),
            ("insomnia", "бессонница", "I've been dealing with insomnia."),
            ("clutter", "беспорядок", "I need to declutter my room."),
            ("lease", "договор аренды", "The lease expires in June."),
            ("deposit", "залог/вклад", "I paid a deposit for the flat."),
            ("appliance", "бытовой прибор", "The washing machine broke."),
            ("bin", "мусорное ведро", "Please take out the bin."),
            ("recycling", "переработка", "Put plastics in the recycling bin."),
            ("budget", "бюджет", "I'm trying to stick to my budget."),
            ("meal prep", "подготовка еды", "I do meal prep on Sundays."),
            ("DIY", "сделай сам", "I love DIY home projects."),
            ("plumber", "сантехник", "We need to call a plumber."),
            ("power cut", "отключение электричества", "There was a power cut last night."),
            ("neighbourhood watch", "соседский дозор", "We have a neighbourhood watch."),
            ("piggybank", "копилка", "Save coins in a piggybank."),
            ("to-do list", "список дел", "I write a to-do list every morning."),
        ]
    },
    "emotions": {
        "name": "😊 Эмоции и чувства",
        "words": [
            ("anxious", "тревожный", "I feel anxious before exams."),
            ("overwhelmed", "подавленный", "I feel overwhelmed with work."),
            ("grateful", "благодарный", "I'm grateful for your help."),
            ("frustrated", "раздражённый", "I get frustrated in traffic."),
            ("relieved", "облегчённый", "I felt so relieved after the exam."),
            ("excited", "взволнованный/радостный", "I'm so excited about the trip!"),
            ("disappointed", "разочарованный", "I was disappointed by the results."),
            ("confident", "уверенный", "She spoke in a confident voice."),
            ("jealous", "завистливый", "Don't be jealous of others."),
            ("proud", "гордый", "I'm so proud of you!"),
            ("bored", "скучающий", "I'm bored — suggest something."),
            ("nervous", "нервный", "I get nervous speaking in public."),
            ("homesick", "тоскующий по дому", "I feel homesick when I travel."),
            ("motivated", "мотивированный", "I feel very motivated today!"),
            ("exhausted", "измотанный", "I'm exhausted after that meeting."),
            ("cheerful", "весёлый", "She's always cheerful in the morning."),
            ("upset", "расстроенный", "Don't be upset, it happens."),
            ("content", "довольный", "I feel content with my life."),
            ("stressed", "в стрессе", "I've been very stressed lately."),
            ("embarrassed", "смущённый", "I was so embarrassed!"),
            ("furious", "в ярости", "She was absolutely furious."),
            ("melancholy", "меланхоличный", "I feel melancholy on rainy days."),
            ("nostalgic", "ностальгирующий", "This song makes me nostalgic."),
            ("indifferent", "безразличный", "He seemed indifferent to the news."),
            ("ecstatic", "в восторге", "She was ecstatic about the results!"),
            ("horrified", "ужасающий/потрясённый", "I was horrified by what happened."),
            ("puzzled", "озадаченный", "I'm puzzled by his behaviour."),
            ("thrilled", "взволнованный (положительно)", "I'm absolutely thrilled!"),
            ("heartbroken", "с разбитым сердцем", "She was heartbroken after the breakup."),
            ("serene", "безмятежный", "I feel serene after meditation."),
            ("irritated", "раздражённый", "Stop tapping, it's irritating me."),
            ("touched", "тронутый", "I was really touched by his words."),
            ("disgusted", "отвращение", "I was disgusted by that behaviour."),
            ("amazed", "поражённый", "I was amazed by the view."),
            ("longing", "тоска/стремление", "I have a longing for home."),
        ]
    },
    "health": {
        "name": "💪 Здоровье",
        "words": [
            ("symptom", "симптом", "What are your symptoms?"),
            ("prescription", "рецепт", "Do you have a prescription?"),
            ("appointment", "приём врача", "I need to make an appointment."),
            ("allergic", "аллергичный", "I'm allergic to penicillin."),
            ("recovery", "выздоровление", "He's in recovery after surgery."),
            ("surgery", "операция", "She had surgery last week."),
            ("dosage", "дозировка", "What's the correct dosage?"),
            ("side effect", "побочный эффект", "This medicine has side effects."),
            ("diagnosis", "диагноз", "The diagnosis was unexpected."),
            ("insurance", "страховка", "Do you have health insurance?"),
            ("workout", "тренировка", "I do a workout every morning."),
            ("diet", "диета/питание", "A balanced diet is important."),
            ("mental health", "психическое здоровье", "Mental health matters too."),
            ("immune system", "иммунная система", "Boost your immune system."),
            ("blood pressure", "давление", "My blood pressure is high."),
            ("painkiller", "обезболивающее", "I took a painkiller for headache."),
            ("check-up", "медосмотр", "I need a check-up this year."),
            ("sprain", "растяжение", "I sprained my ankle running."),
            ("contagious", "заразный", "Is it contagious?"),
            ("chronic", "хронический", "She has chronic back pain."),
            ("inflammation", "воспаление", "There's some inflammation around the joint."),
            ("vaccine", "вакцина", "Have you had the vaccine?"),
            ("nausea", "тошнота", "I feel nausea in the morning."),
            ("dizzy", "головокружение", "I feel dizzy when I stand up."),
            ("dehydrated", "обезвоженный", "Drink water — you're dehydrated."),
            ("rash", "сыпь", "I have a rash on my arm."),
            ("fracture", "перелом", "She has a fracture in her wrist."),
            ("physiotherapy", "физиотерапия", "I go to physiotherapy twice a week."),
            ("well-being", "благополучие", "Focus on your well-being."),
            ("calories", "калории", "How many calories is that?"),
            ("supplement", "добавка", "I take vitamin supplements."),
            ("stretching", "растяжка", "Do some stretching before exercise."),
            ("sedentary", "малоподвижный", "A sedentary lifestyle is unhealthy."),
            ("hydration", "гидратация", "Proper hydration is essential."),
            ("metabolism", "метаболизм", "Exercise boosts your metabolism."),
        ]
    },
    "technology": {
        "name": "💻 Технологии",
        "words": [
            ("update", "обновление", "Please install the latest update."),
            ("password", "пароль", "Use a strong password."),
            ("download", "скачать", "How long will the download take?"),
            ("backup", "резервная копия", "Always make a backup of your files."),
            ("software", "программное обеспечение", "This software needs updating."),
            ("hardware", "оборудование", "The hardware is outdated."),
            ("bandwidth", "пропускная способность", "I need more bandwidth."),
            ("encrypted", "зашифрованный", "The message is encrypted."),
            ("artificial intelligence", "искусственный интеллект", "AI is changing everything."),
            ("algorithm", "алгоритм", "The algorithm decides what you see."),
            ("cloud storage", "облачное хранилище", "I use cloud storage for photos."),
            ("cybersecurity", "кибербезопасность", "Cybersecurity is very important."),
            ("notification", "уведомление", "I turned off notifications."),
            ("server", "сервер", "The server crashed again."),
            ("screen time", "время у экрана", "I'm reducing my screen time."),
            ("virtual reality", "виртуальная реальность", "VR is amazing for gaming."),
            ("data privacy", "конфиденциальность данных", "Protect your data privacy."),
            ("bug", "ошибка в программе", "There's a bug in the app."),
            ("crash", "сбой/зависание", "My laptop crashed again."),
            ("reboot", "перезагрузка", "Try rebooting the device."),
            ("interface", "интерфейс", "The interface is very user-friendly."),
            ("streaming", "стриминг", "I prefer streaming over cable TV."),
            ("cache", "кэш", "Clear your browser cache."),
            ("firewall", "файрвол", "The firewall blocked the connection."),
            ("phishing", "фишинг", "Watch out for phishing emails."),
            ("plugin", "плагин", "Install this plugin for better results."),
            ("debugging", "отладка", "The developer spent hours debugging."),
            ("open source", "открытый код", "This is open source software."),
            ("latency", "задержка", "High latency causes lag in games."),
            ("processor", "процессор", "The new processor is much faster."),
            ("pixel", "пиксель", "This screen has 4K pixels."),
            ("wireless", "беспроводной", "Connect to the wireless network."),
            ("malware", "вредоносное ПО", "The malware infected the system."),
            ("two-factor authentication", "двухфакторная аутентификация", "Enable two-factor authentication."),
            ("digital footprint", "цифровой след", "Be aware of your digital footprint."),
        ]
    },
    "shopping": {
        "name": "🛒 Покупки",
        "words": [
            ("discount", "скидка", "Is there a discount on this?"),
            ("refund", "возврат денег", "I'd like a refund please."),
            ("receipt", "чек", "I need a receipt for this."),
            ("exchange", "обмен", "Can I exchange this for a larger size?"),
            ("out of stock", "нет в наличии", "Sorry, it's out of stock."),
            ("fitting room", "примерочная", "Where is the fitting room?"),
            ("bargain", "выгодная покупка", "This is a real bargain!"),
            ("affordable", "доступный по цене", "This brand is quite affordable."),
            ("overpriced", "переоценённый", "That restaurant is overpriced."),
            ("loyalty card", "карта лояльности", "Do you have a loyalty card?"),
            ("sale", "распродажа", "Everything is on sale today!"),
            ("warranty", "гарантия", "Is there a warranty on this?"),
            ("checkout", "касса/оплата", "There's a long queue at checkout."),
            ("buy in bulk", "покупать оптом", "It's cheaper to buy in bulk."),
            ("second-hand", "подержанный", "I love second-hand shops."),
            ("impulse buy", "импульсивная покупка", "It was an impulse buy."),
            ("clearance", "финальная распродажа", "I found it in the clearance section."),
            ("premium", "премиальный", "This is a premium product."),
            ("counterfeit", "поддельный", "Be careful — that bag looks counterfeit."),
            ("browse", "смотреть/листать", "I just came in to browse."),
            ("in season", "в сезоне", "Strawberries are cheaper in season."),
            ("price tag", "ценник", "There's no price tag on this."),
            ("shoplifting", "кража в магазине", "Shoplifting is a serious crime."),
            ("retailer", "розничный продавец", "This retailer ships worldwide."),
            ("wholesale", "оптовый", "I buy wholesale and resell."),
            ("markdowns", "снижение цен", "Check for markdowns in January."),
            ("gift voucher", "подарочный сертификат", "Can I pay with a gift voucher?"),
            ("exchange policy", "политика обмена", "What's your exchange policy?"),
            ("try on", "примерить", "Can I try this on?"),
            ("limited edition", "ограниченный выпуск", "This is a limited edition item."),
            ("designer brand", "дизайнерский бренд", "She only wears designer brands."),
            ("customer service", "обслуживание клиентов", "Their customer service is excellent."),
            ("window shopping", "смотреть витрины", "I love window shopping downtown."),
            ("queue", "очередь", "The queue at checkout is very long."),
            ("payment method", "способ оплаты", "What payment methods do you accept?"),
        ]
    },
    "people": {
        "name": "🤝 Общение и люди",
        "words": [
            ("introduce", "представлять", "Let me introduce you to my friend."),
            ("acquaintance", "знакомый", "He's just an acquaintance."),
            ("relationship", "отношения", "We have a great working relationship."),
            ("gossip", "сплетни", "I don't like office gossip."),
            ("polite", "вежливый", "Always be polite to customers."),
            ("rude", "грубый", "That was very rude of him."),
            ("reliable", "надёжный", "She is the most reliable person I know."),
            ("supportive", "поддерживающий", "My friends are very supportive."),
            ("honest", "честный", "Be honest with me, please."),
            ("stubborn", "упрямый", "He's so stubborn sometimes!"),
            ("approachable", "открытый/доступный", "The manager is very approachable."),
            ("first impression", "первое впечатление", "First impressions matter a lot."),
            ("small talk", "светская беседа", "He's great at small talk."),
            ("get along", "ладить", "Do you get along with your boss?"),
            ("misunderstanding", "недопонимание", "It was just a misunderstanding."),
            ("argument", "спор/ссора", "We had a small argument yesterday."),
            ("compliment", "комплимент", "She gave me a nice compliment."),
            ("peer pressure", "давление сверстников", "Resist peer pressure."),
            ("mentor", "наставник", "I need a good mentor at work."),
            ("empathy", "эмпатия", "She shows great empathy to others."),
            ("boundaries", "границы", "It's okay to set personal boundaries."),
            ("compromise", "компромисс", "We reached a compromise."),
            ("confrontation", "конфронтация", "I try to avoid confrontation."),
            ("assertive", "напористый/уверенный", "Be assertive, not aggressive."),
            ("introvert", "интроверт", "I'm an introvert — I need quiet time."),
            ("extrovert", "экстраверт", "She's a real extrovert at parties."),
            ("networking", "нетворкинг", "Good networking opens many doors."),
            ("influential", "влиятельный", "He's a very influential person."),
            ("trustworthy", "заслуживающий доверия", "Is she trustworthy?"),
            ("charismatic", "харизматичный", "He's very charismatic on stage."),
            ("toxic", "токсичный", "I left that toxic friendship."),
            ("boundaries", "личные границы", "She needs to set boundaries."),
            ("generous", "щедрый", "He's incredibly generous with his time."),
            ("selfish", "эгоистичный", "Don't be so selfish!"),
            ("diplomatic", "дипломатичный", "Try to be more diplomatic."),
        ]
    },
    "nature": {
        "name": "🌍 Природа и окружение",
        "words": [
            ("hurricane", "ураган", "A hurricane is approaching the coast."),
            ("drought", "засуха", "The drought destroyed the harvest."),
            ("earthquake", "землетрясение", "There was an earthquake last night."),
            ("flood", "наводнение", "The flood damaged many houses."),
            ("wildlife", "дикая природа", "Protect the local wildlife."),
            ("endangered", "исчезающий", "This species is endangered."),
            ("ecosystem", "экосистема", "We must protect our ecosystem."),
            ("climate change", "изменение климата", "Climate change is real."),
            ("renewable energy", "возобновляемая энергия", "Solar is renewable energy."),
            ("pollution", "загрязнение", "Air pollution is a big problem."),
            ("landscape", "пейзаж", "The landscape is breathtaking!"),
            ("forecast", "прогноз", "The weather forecast says rain."),
            ("humid", "влажный", "It's very humid today."),
            ("breeze", "лёгкий ветер", "There's a pleasant sea breeze."),
            ("glacier", "ледник", "Glaciers are melting fast."),
            ("deforestation", "вырубка лесов", "Deforestation is a global problem."),
            ("recycle", "перерабатывать", "We should all recycle more."),
            ("sustainable", "устойчивый/экологичный", "Buy sustainable products."),
            ("habitat", "среда обитания", "This is the animal's natural habitat."),
            ("avalanche", "лавина", "The avalanche blocked the road."),
            ("tidal wave", "приливная волна", "A tidal wave hit the coast."),
            ("fossil fuel", "ископаемое топливо", "We need to reduce fossil fuels."),
            ("carbon footprint", "углеродный след", "Reduce your carbon footprint."),
            ("biodiversity", "биоразнообразие", "The Amazon has incredible biodiversity."),
            ("predator", "хищник", "The wolf is the top predator here."),
            ("migration", "миграция", "Bird migration is amazing to watch."),
            ("bloom", "цвести", "The cherry trees bloom in spring."),
            ("current", "течение", "The ocean current is very strong."),
            ("altitude", "высота над уровнем моря", "We're at 3000m altitude."),
            ("terrain", "местность/рельеф", "The terrain is very rocky."),
            ("canopy", "навес/полог леса", "Birds live in the forest canopy."),
            ("estuary", "эстуарий", "The river meets the sea at the estuary."),
            ("tornado", "торнадо", "A tornado warning was issued."),
            ("erosion", "эрозия", "Coastal erosion is destroying the cliffs."),
            ("reforestation", "лесовосстановление", "Reforestation helps fight climate change."),
        ]
    },
    "finance": {
        "name": "💰 Финансы и деньги",
        "words": [
            ("budget", "бюджет", "Stick to your monthly budget."),
            ("savings", "сбережения", "I have savings for emergencies."),
            ("investment", "инвестиция", "Real estate is a good investment."),
            ("loan", "кредит", "I took a loan to buy a car."),
            ("interest rate", "процентная ставка", "The interest rate is very high."),
            ("mortgage", "ипотека", "We applied for a mortgage."),
            ("debt", "долг", "I'm trying to pay off my debt."),
            ("income", "доход", "His income doubled this year."),
            ("expenses", "расходы", "Track your monthly expenses."),
            ("profit", "прибыль", "The company made a huge profit."),
            ("loss", "убыток", "We made a loss last quarter."),
            ("stock", "акция", "Apple stock went up today."),
            ("dividend", "дивиденд", "I earn dividends from my shares."),
            ("inflation", "инфляция", "Inflation is rising fast."),
            ("tax", "налог", "Don't forget to pay your taxes."),
            ("invoice", "счёт-фактура", "I'll send you the invoice today."),
            ("refund", "возврат", "I'm waiting for my tax refund."),
            ("transaction", "транзакция", "The transaction failed."),
            ("balance", "баланс", "Check your account balance."),
            ("withdraw", "снять деньги", "I need to withdraw some cash."),
            ("deposit", "депозит/вклад", "I made a deposit this morning."),
            ("cryptocurrency", "криптовалюта", "Bitcoin is a cryptocurrency."),
            ("portfolio", "портфель", "Diversify your investment portfolio."),
            ("pension", "пенсия", "I'm saving for my pension."),
            ("bankrupt", "банкрот", "The company went bankrupt."),
            ("insurance", "страховка", "Get car insurance before driving."),
            ("premium", "страховой взнос", "The monthly premium is €50."),
            ("net worth", "чистая стоимость активов", "Her net worth is impressive."),
            ("overdraft", "овердрафт", "I'm in my overdraft this month."),
            ("compound interest", "сложные проценты", "Compound interest grows your savings."),
            ("frugal", "экономный", "She is very frugal with money."),
            ("instalment", "взнос/платёж", "I pay in monthly instalments."),
            ("subsidy", "субсидия", "The government offers energy subsidies."),
            ("income tax", "подоходный налог", "Income tax is deducted automatically."),
            ("financial literacy", "финансовая грамотность", "Financial literacy is essential."),
        ]
    },
    "education": {
        "name": "🎓 Образование",
        "words": [
            ("curriculum", "учебная программа", "The curriculum was updated last year."),
            ("scholarship", "стипендия", "She won a full scholarship."),
            ("degree", "степень/диплом", "He has a degree in engineering."),
            ("thesis", "дипломная работа", "I'm writing my master's thesis."),
            ("tutor", "репетитор", "I hired a private tutor."),
            ("enroll", "записаться/поступить", "I enrolled in an online course."),
            ("assignment", "задание", "Submit your assignment by Friday."),
            ("seminar", "семинар", "We have a seminar every Thursday."),
            ("lecture", "лекция", "The lecture was very interesting."),
            ("essay", "эссе", "I need to write a 2000-word essay."),
            ("grade", "оценка", "What grade did you get?"),
            ("pass", "сдать/пройти", "Did you pass the exam?"),
            ("fail", "провалить", "I failed my driving test."),
            ("retake", "пересдача", "I need to retake the test."),
            ("plagiarism", "плагиат", "Plagiarism is a serious offence."),
            ("bibliography", "библиография", "Add a bibliography to your essay."),
            ("peer review", "взаимная проверка", "The paper went through peer review."),
            ("internship", "стажировка", "She got an internship at Google."),
            ("graduate", "выпускник/окончить", "He graduated with honours."),
            ("undergraduate", "студент бакалавриата", "She's an undergraduate student."),
            ("postgraduate", "аспирант/магистрант", "He's doing postgraduate research."),
            ("distance learning", "дистанционное обучение", "I prefer distance learning."),
            ("coursework", "курсовая работа", "Coursework counts for 40%."),
            ("revise", "повторять/пересматривать", "I need to revise for my exams."),
            ("syllabus", "программа курса", "Check the course syllabus."),
            ("mentor", "наставник", "My mentor helped me a lot."),
            ("faculty", "факультет/преподаватели", "The faculty is excellent."),
            ("extracurricular", "внеучебный", "Join extracurricular activities."),
            ("attendance", "посещаемость", "Attendance is mandatory."),
            ("critical thinking", "критическое мышление", "Critical thinking is a key skill."),
            ("motivation", "мотивация", "Find your learning motivation."),
            ("concentrate", "сосредоточиться", "I can't concentrate in noisy places."),
            ("deadline", "срок сдачи", "The essay deadline is Monday."),
            ("academic", "академический", "Academic writing is very formal."),
            ("dropout", "бросивший учёбу", "He became a dropout at 18."),
        ]
    },
    "entertainment": {
        "name": "🎬 Развлечения и досуг",
        "words": [
            ("blockbuster", "блокбастер", "That was a real blockbuster!"),
            ("plot twist", "поворот сюжета", "The plot twist was unexpected."),
            ("binge-watch", "смотреть запоем", "I binge-watched the whole series."),
            ("soundtrack", "саундтрек", "The soundtrack is amazing."),
            ("premiere", "премьера", "We went to the movie premiere."),
            ("cast", "состав актёров", "The cast is star-studded."),
            ("director", "режиссёр", "Who is the director of this film?"),
            ("sequel", "сиквел/продолжение", "The sequel was better than the original."),
            ("box office", "кассовые сборы", "It broke box office records."),
            ("genre", "жанр", "What's your favourite genre?"),
            ("documentary", "документальный фильм", "I love watching documentaries."),
            ("concert", "концерт", "We have concert tickets for Saturday."),
            ("gig", "выступление/концерт", "I saw them at a small gig."),
            ("album", "альбом", "Their new album is incredible."),
            ("lyrics", "текст песни", "I love the lyrics of this song."),
            ("festival", "фестиваль", "The music festival lasts 3 days."),
            ("exhibition", "выставка", "There's an art exhibition downtown."),
            ("gallery", "галерея", "Let's visit the gallery on Sunday."),
            ("performance", "выступление", "Her performance was breathtaking."),
            ("rehearsal", "репетиция", "The rehearsal is at 7 PM."),
            ("applause", "аплодисменты", "The audience gave a standing ovation."),
            ("encore", "бис", "They played two encores!"),
            ("intermission", "антракт", "We can grab a drink at intermission."),
            ("ticket", "билет", "I booked the tickets online."),
            ("sold out", "распродано", "The show is sold out!"),
            ("fan", "поклонник/фанат", "I'm a big fan of this band."),
            ("trivia", "занимательные факты", "Do you know any fun trivia?"),
            ("escapism", "эскапизм", "Reading is pure escapism for me."),
            ("comedy", "комедия", "I need a good comedy to cheer up."),
            ("thriller", "триллер", "I love psychological thrillers."),
            ("rating", "рейтинг", "This film has a 9/10 rating."),
            ("subscription service", "сервис подписки", "Which subscription service do you use?"),
            ("stream", "стриминг/трансляция", "I stream music at work."),
            ("podcast", "подкаст", "Have you listened to this podcast?"),
            ("virtual event", "онлайн-мероприятие", "I joined a virtual event last night."),
        ]
    },
}

ALL_THEME_KEYS = list(VOCABULARY_THEMES.keys())
TOTAL_WORDS = sum(len(t["words"]) for t in VOCABULARY_THEMES.values())
